[2025-10-25T04:18:45.482+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-25T04:18:45.519+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: support_ticket_pipeline.train_small_model manual__2025-10-25T04:17:53.411720+00:00 [queued]>
[2025-10-25T04:18:45.534+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: support_ticket_pipeline.train_small_model manual__2025-10-25T04:17:53.411720+00:00 [queued]>
[2025-10-25T04:18:45.534+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-25T04:18:45.544+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): train_small_model> on 2025-10-25 04:17:53.411720+00:00
[2025-10-25T04:18:45.553+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'support_ticket_pipeline', 'train_small_model', 'manual__2025-10-25T04:17:53.411720+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/support_ticket_pipeline.py', '--cfg-path', '/tmp/tmpnphqwtr4']
[2025-10-25T04:18:45.556+0000] {standard_task_runner.py:91} INFO - Job 36: Subtask train_small_model
[2025-10-25T04:18:45.556+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=652) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-25T04:18:45.563+0000] {standard_task_runner.py:64} INFO - Started process 661 to run task
[2025-10-25T04:18:45.634+0000] {task_command.py:426} INFO - Running <TaskInstance: support_ticket_pipeline.train_small_model manual__2025-10-25T04:17:53.411720+00:00 [running]> on host 120c55d1f138
[2025-10-25T04:18:45.740+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='support_ticket_pipeline' AIRFLOW_CTX_TASK_ID='train_small_model' AIRFLOW_CTX_EXECUTION_DATE='2025-10-25T04:17:53.411720+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-25T04:17:53.411720+00:00'
[2025-10-25T04:18:45.741+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-25T04:18:49.341+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-25T04:18:49.346+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/support_ticket_pipeline.py", line 147, in train_small_model
    y = npz["labels"]
        ~~~^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/numpy/lib/_npyio_impl.py", line 258, in __getitem__
    return format.read_array(bytes,
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/numpy/lib/format.py", line 822, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False
[2025-10-25T04:18:49.429+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=support_ticket_pipeline, task_id=train_small_model, run_id=manual__2025-10-25T04:17:53.411720+00:00, execution_date=20251025T041753, start_date=20251025T041845, end_date=20251025T041849
[2025-10-25T04:18:49.478+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 36 for task train_small_model (Object arrays cannot be loaded when allow_pickle=False; 661)
[2025-10-25T04:18:49.550+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-25T04:18:49.693+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-25T04:18:49.697+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
